server.port=8080
spring.application.name=ApiGateway
# URL-urile microserviciilor CRUD
crud.create.url=http://localhost:8081
crud.read.url=http://localhost:8082
crud.update.url=http://localhost:8083
crud.delete.url=http://localhost:8084
